[tool.poetry]
name = "dino-screen"
version = "0.1.0"
description = ""
authors = ["Paul Morris <ptmorris03@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
